#开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: website
    password: 4CiGYNcerf
    url: jdbc:mysql://120.79.2.77/website?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8080